version: '1.0.0.{build}'
image: Ubuntu
services:
  - docker
configuration: Release
environment:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
build_script:
  - dotnet build ./src/TestEnvironment.Docker/TestEnvironment.Docker.csproj
test_script:
  - dotnet test ./test/TestEnvironment.Docker.Tests/TestEnvironment.Docker.Tests.csproj
artifacts:
  - path: '**\*.nupkg'